export function homePage() {

  gsap.registerPlugin(ScrollTrigger, SplitText);

  // DESKTOP ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  if(!isMobile() || window.innerWidth > 1024 ) {


      let sections = gsap.utils.toArray(".side-scroll .panel");
      let pWidth
      let totalWidth

      let scrollWidth = function() {
        totalWidth = 0
        sections.forEach(panel => {
          pWidth = panel.offsetWidth
          totalWidth += pWidth
        })
        return totalWidth

      }
      scrollWidth()



    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // HYBRID SCROLL ///////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////

    ScrollTrigger.create({
      trigger: "#work",
      start: () => + window.innerWidth,
      end: ()=> "+=" + ((- window.innerHeight + 90) + document.querySelector("#work").offsetHeight),
      // markers: true,
      pin: ".marquize-stripe"
    })
    ScrollTrigger.create({
          trigger: "#work",
          start: () => + window.innerWidth,
          end: ()=> "+=" + ((- window.innerHeight + 90) + document.querySelector("#work").offsetHeight) ,
          pin: "#quote",
    })
     ScrollTrigger.create({
          trigger: "#work",
          start: () => + window.innerWidth / 2,
          end: ()=> "+=" + ((- window.innerHeight + 90) + document.querySelector("#work").offsetHeight * 1.5) ,
          onEnter: () => {
               eyesLottie.play()
          },
          onEnterBack: () => {
               eyesLottie.play()
          },
          onLeave: () => {
               eyesLottie.pause()
          },
          onLeaveBack: () => {
               eyesLottie.pause()
          },
    })
    gsap.to("#work", {
      x: - totalWidth, // this total width is generated by another code snippet
      ease: "none",
      scrollTrigger: {
        trigger: ".side-scroll",
        start: "top top",
        pin: "#work",
        scrub: .1,
        //snap: directionalSnap(1 / (sections.length - 1)),
        end: () => "+=" + sections.length * window.innerHeight * 2,
      }
    });

    // WORK BUTTON PIN/////////////////////////////////////////////////////////////////////////////////////////
    let workButton = document.querySelector("#work .button")
    let btnLabel = workButton.querySelector("span")
    let btnIco = workButton.querySelector("img")
    let sidePush
    let btnTop
    let btnBottom
    if(window.innerWidth > 1024) {
        sidePush = workButton.offsetWidth / 4
    } else if (window.innerWidth <= 1024) {
        sidePush = workButton.offsetWidth / 5
    }
    if(window.innerWidth <= 1920) {
      btnTop = (window.innerWidth + workButton.offsetTop + workButton.offsetHeight + 80) - window.innerHeight
      btnBottom = (((window.innerHeight / 100) * 45) - 40)
    } else if(window.innerWidth > 1920) {
      btnTop = (window.innerWidth + workButton.offsetTop + workButton.offsetHeight + 100) - window.innerHeight
      btnBottom = (((window.innerHeight / 100) * 45))
    }
    gsap.set(btnIco, {rotate: -45})
    let btnAnim = gsap.timeline({
      scrollTrigger: {
        trigger:workButton,
        scrub:true,
        start:() => + btnTop,
        end: () => "+=" + btnBottom,
        invalidateOnRefresh: true
      }
    })
    btnAnim.to(workButton, {
      height: "55vh",
      ease: "none",
      duration: 0.0001,
    });
    btnAnim.to(btnLabel, {
      x:sidePush,
      ease: "none",
      duration: 0.0001,
    }, "<");
    btnAnim.to(btnIco, {
      x: -sidePush,
      ease: "none",
      duration: 0.0001,
    }, "<");

     workButton.addEventListener("mouseenter", function() {
          gsap.to(btnLabel, {
               xPercent: 10,
               duration: .35,
               ease: "power4"
          })
          gsap.to(btnIco, {
               xPercent: -10,
               rotate: 0,
               duration: .35,
               ease: "power4"
          })
     })
     workButton.addEventListener("mouseleave", function() {
          gsap.to(btnLabel, {
               xPercent: 0,
               duration: .35,
               ease: "power4"
          })
          gsap.to(btnIco, {
               xPercent: 0,
               rotate: -45,
               duration: .35,
               ease: "power4"
          })
     })
    // END WORK BUTTON PIN/////////////////////////////////////////////////////////////////////////////////////////


    let workIco = document.querySelector("#work .spin-text")
    gsap.to(workIco, {
      rotateZ: 360,
      duration: 12,
      repeat: -1,
      ease: "linear",
      scrollTrigger: {
        trigger: "#work",
        start: () => + window.innerWidth /2,
        end: ()=> "+=" + ((- window.innerHeight + 80) + document.querySelector("#work").offsetHeight) ,
        toggleActions: "play none play pause",
      }
    })

    // IN VIEW ITEM WITHIN WORK
    const vItem = gsap.utils.toArray(".box-anim")
    gsap.set(vItem, {scale: .5, yPercent: 50, rotateZ: 15,})
    vItem.forEach(item => {
      gsap.to(item, {
        duration: 1,
        yPercent: 0,
        scale: 1,
        rotateZ: 0,
        ease: "power4",
        scrollTrigger: {
          start:() => + (window.innerWidth + item.offsetTop * 1.1) - window.innerHeight,
          end: () => + window.innerWidth + item.offsetTop,
          trigger: item,
          toggleActions: "play none none reverse",
          scrub: true
        }
      })
    })

    let quote = new SplitText("#quote .split.chars", { type: "words" })

    gsap.set(quote.words, {
      filter: "blur(5px)",
      rotateZ: 10,
      xPercent: 100,
      opacity: 0,
    })
    gsap.to(quote.words, {
        transformOrigin: "0% 100%",
        duration: .8,
        stagger: {
            amount: .4
        },
        filter: "blur(0px)",
        rotateZ: 0,
        xPercent: 0,
        opacity: 1,
        ease: "linear",
        scrollTrigger: {
          trigger: "#work",
          start: () => + window.innerWidth - window.innerHeight / 1.5,
          end: () => + window.innerWidth ,
          toggleActions: "play none none reverse",
          scrub: true
        }
    })



    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // Side scroll setup ///////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    let sideScroll = gsap.to(".side-scroll", {
      x: () => {
        totalWidth = 0
        sections.forEach(panel => {
          pWidth = panel.offsetWidth
          totalWidth += pWidth
        })
        return -totalWidth
      }, // this total width is generated by another code snippet
      ease: "none", // <-- IMPORTANT!
      scrollTrigger: {
        trigger: ".side-scroll",
        start: "top top",
        pin: ".side-scroll",
        scrub: 0.1,
        end: () => "+=" + sections.length * window.innerHeight * 2,
        invalidateOnRefresh: true,
      }
    });


    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // MEDIA BOXES ///////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////

    gsap.utils.toArray(".media-box").forEach(box => {
      let img = box.querySelector("img")
      let imgHover = gsap.timeline({paused: true})
      imgHover.to(img, {
          scaleX: 1.05,
          scaleY: 1.05,
          duration: .3,
          ease:"power4.inOut"
      })

      gsap.from(box, {
        rotate: 15,
        scale: .5,
        xPercent: 20,
        duration: 1,
        ease: "power4",
        scrollTrigger: {
          containerAnimation: sideScroll,
          trigger: box,
          start: "left 100%",
          toggleActions: "play none none reverse",
        }
      })
      box.addEventListener("mouseenter", function() {
            imgHover.restart()
      })
      box.addEventListener("mouseleave", function() {
            imgHover.reverse()
      })
    })

    // TEXT ANIM FOR side Scroll
    gsap.utils.toArray(".side-scroll .split.chars").forEach(title => {
        let hTitle = new SplitText(title, { type: "chars" })

        let hTimeline = gsap.timeline({
          scrollTrigger: {
               containerAnimation: sideScroll,
               trigger: title,
               start:"left 90%",
               toggleActions: "play none none reverse"
          }
        })

        gsap.set(hTitle.chars, {
          filter: "blur(5px)",
          rotateZ: 10,
          xPercent: 100,
          opacity: 0,
        })

        gsap.to(hTitle.chars, {
          transformOrigin: "0% 100%",
          duration: .8,
          stagger: {
              amount: .4
          },
          filter: "blur(0px)",
          xPercent: 0,
          opacity: 1,
          rotateZ: 0,
          ease: "power4",
          scrollTrigger: {
            containerAnimation: sideScroll,
            trigger: title,
            start:"left 90%",
            toggleActions: "play none none reverse",
          }
      })
    })



    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // MEDIA ///////////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    gsap.to("#media header", {
      x: document.querySelector("#media").offsetWidth - window.innerWidth,
      ease: "linear",
      scrollTrigger: {
        containerAnimation: sideScroll,
        trigger: "#media",
        start: "left left",
        end: "right right",
        toggleActions: "play none none reverse",
        scrub: true
      }
    })

    // Media lottie
    ScrollTrigger.create({
      containerAnimation: sideScroll,
      trigger: "#media",
      start: "left right",
      end: "right 20%",
      onEnter: () => {
        cameraLottie.play()
      },
      onEnterBack: () => {
        cameraLottie.play()
      },
      onLeave: () => {
        cameraLottie.pause()
      },
      onLeaveBack: () => {
        cameraLottie.pause()
      },
    })



    // ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // // CONTACT BG ///////////////////////////////////////////////////////////////////////////////////////////////
    // ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
      let contactIco = document.querySelector("#contact .spin-text")
      gsap.to(contactIco, {
        rotateZ: 360,
        duration: 12,
        repeat: -1,
        ease: "linear",
        scrollTrigger: {
          containerAnimation: sideScroll,
          trigger: contactIco,
          start: "left right",
          toggleActions: "play none none reverse",
        }
      })

    gsap.to("#contact-bg", {
      scaleX: 1,
      ease: "linear",
      scrollTrigger: {
        containerAnimation: sideScroll,
        trigger: "#media",
        start: "right 95%",
        toggleActions: "play none none reverse",
        scrub: true,
        onEnter: () => {
          carLottie.play()
        },
        onEnterBack: () => {
          carLottie.play()
        },
        onLeave: () => {
          carLottie.pause()
        },
        onLeaveBack: () => {
          carLottie.pause()
        },
      }
    })

    gsap.from(["#contact header h2", "#contact .ws-xl-17, #contact .header-icon"] , {
      x: window.innerWidth/4,
      ease: "linear",
      stagger: {
        amount: .1
      },
      scrollTrigger: {
        containerAnimation: sideScroll,
        trigger: "#media",
        start: "right 70%",
        end: "right left",
        toggleActions: "play none none reverse",
        scrub: true
      }
    })

  }

  // MOBILE ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  if(isMobile() || window.innerWidth < 1024 ) {

    // ANIMATE LOTTIES ///////////////////////////////////////////////////////////////////////////////////////////////////////////
    ScrollTrigger.create({
      trigger: "#hero .lottie-icon",
      start: "top bottom",
      end: "bottom top",
      onEnter: () => {
          teethLottie.play()
        },
        onEnterBack: () => {
          teethLottie.play()
        },
        onLeave: () => {
          teethLottie.pause()
        },
    })

     ScrollTrigger.create({
          trigger: "#quote",
          start: "top bottom",
          end: "bottom top" ,
          onEnter: () => {
               eyesLottie.play()
          },
          onEnterBack: () => {
               eyesLottie.play()
          },
          onLeave: () => {
               eyesLottie.pause()
          },
          onLeaveBack: () => {
               eyesLottie.pause()
          },
    })

    ScrollTrigger.create({
      trigger: "#media .lottie-icon",
      start: "top bottom",
      end: "bottom top",
      onEnter: () => {
          cameraLottie.play()
        },
        onEnterBack: () => {
          cameraLottie.play()
        },
        onLeave: () => {
          cameraLottie.pause()
        },
        onLeaveBack: () => {
          cameraLottie.pause()
        },
    })

    ScrollTrigger.create({
      trigger: "#contact .lottie-icon",
      start: "top bottom",
      end: "bottom top",
      onEnter: () => {
          carLottie.play()
        },
        onEnterBack: () => {
          carLottie.play()
        },
        onLeave: () => {
          carLottie.pause()
        },
        onLeaveBack: () => {
          carLottie.pause()
        },
    })

    // ANIMATE WORK BOXES ////////////////////////////////////////////////////////////////////////////////////////////////////////
    const vItem = gsap.utils.toArray("#work .work-box:not(.first)")
    vItem.forEach(item => {
      gsap.set(item, {scale: .5, yPercent: 15, opacity: 0, rotateZ: 15,})
      gsap.to(item, {
        duration: 1,
        yPercent: 0,
        scale: 1,
        rotateZ: 0,
        opacity: 1,
        ease: "power4",
        scrollTrigger: {
          start:"top bottom",
          trigger: item,
          toggleActions: "play none none reverse",
        }
      })
    })

    // QUOTE /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     let quote = new SplitText("#quote .split.chars", { type: "words" })

     gsap.set(quote.words, {
          filter: "blur(5px)",
          rotateZ: 15,
          yPercent: 100,
          xPercent: 50,
          opacity: 0,
     })
     gsap.to(quote.words, {
          transformOrigin: "0% 100%",
          duration: .6,
          filter: "blur(0px)",
          rotateZ: 0,
          yPercent: 0,
          xPercent: 0,
          opacity: 1,
          ease: "linear",
          stagger: {
               amount: .5
          },
          scrollTrigger: {
               trigger: "#quote h2",
               start: "top bottom",
               end: "top 50%",
               toggleActions: "play none none reverse",
               scrub: true
          }
     })


    // ANIMATE MEDIA BOXES ////////////////////////////////////////////////////////////////////////////////////////////////////////
    const mItem = gsap.utils.toArray("#media .media-box")
    mItem.forEach(item => {
      let mTl = gsap.timeline({
        scrollTrigger: {
          trigger: item,
          start: "top 90%",
          toggleActions: "play none none reverse",
        }
      })
      let img = item.querySelector("figure")
      let text = item.querySelector(".media-content")
      gsap.set(img, {scale: .5, yPercent: 40, rotateZ: 15,})
      gsap.set(text, {scale: .5, yPercent: 40})

      mTl.to(img, {
        duration: 1,
        yPercent: 0,
        scale: 1,
        rotateZ: 0,
        ease: "power4",
      })
      mTl.to(text, {
        duration: 1,
        yPercent: 0,
        scale: 1,
        ease: "power4",
      }, "-=.9")
    })

    // SPIN TEXT ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    let spinText = gsap.utils.toArray(".spin-text").forEach(st => {
      gsap.to(st, {
        rotateZ: 360,
        duration: 12,
        repeat: -1,
        ease: "linear",
        scrollTrigger: {
          trigger: st,
          start: "top bottom",
          end: "bottom top",
          toggleActions: "play pause play pause",
        }
      })
    })



  }

  // OPEN VIDEO //////////////////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////////////////////////////
  let items = document.querySelectorAll(".work-listing article"),
    closeVid = document.querySelector(".video-close"),
    vidSrc,
    vidModal = gsap.timeline()


    ////// HOVERING ITEMS ///////////////////////////////////////////////////////////////////////////////////////////////////
    items.forEach(item => {

        // OPEN VIDEO MODAL
        item.addEventListener("click", function() {
            if(!isMobile()) {
                smoother.paused(true)
            }
            let thisData = item.dataset.project,
            thisVideo = document.querySelector(`[data-video="${thisData}"]`),
            thisFrame = thisVideo.querySelector("iframe"),
            label = thisVideo.querySelector(".caption")

            let frameSrc = thisFrame.src
            frameSrc += '&autoplay=1'
            thisFrame.src = 'about:blank'
            thisFrame.src = frameSrc

            vidSrc = thisFrame.src
            gsap.set(thisFrame, {yPercent: -35})
            gsap.set(label, {opacity: 0})

            closeVid.dataset.open = thisData;

            vidModal.to(".video-bg", {
                y: "-0%",
                rotate: 0,
                scale: 1,
                duration: 1,
                ease: "expo.inOut",
                onStart: ()=> {
                    gsap.to("#video-wrap", {
                        pointerEvents: "auto",
                    })
                    gsap.set(thisVideo, {zIndex: 2})
                    gsap.to(thisFrame, {
                        display: "block",
                    })
                }
            })
            vidModal.to("#menu", {
                opacity: 0,
                duration: .5,
                ease: "expo",
                pointerEvents: "none",
            }, "<")
            vidModal.to(thisFrame, {
                opacity: 1,
                rotate: 0,
                yPercent: 0,
                duration: 1,
                ease: "expo"
            },"-=.4")
            vidModal.to(closeVid, {
                opacity: 1,
                y: 0,
                duration: 1,
                ease: "expo",
            }, "-=.7")
            vidModal.to(label, {
                opacity: 1,
                duration: 1,
                ease: "expo"
            },"-=.7")

            item.classList.add("active")
            return vidSrc
        })

    })

    closeVid.addEventListener("click", function() {
        let thisData = closeVid.dataset.open,
        thisVideo = document.querySelector(`[data-video="${thisData}"]`),
        thisFrame = thisVideo.querySelector("iframe"),
          label = thisVideo.querySelector(".caption")


        vidModal.to(closeVid, {
            opacity: 0,
            duration: .5,
            y: "-100%",
            ease: "expo.in",
        })
          vidModal.to(label, {
               opacity: 0,
               duration: .5,
               ease: "expo"
          },"<")
        vidModal.to(thisFrame, {
            opacity: 0,
            rotate: -10,
            duration: .5,
            yPercent: -25,
            ease: "expo.in",
            onComplete: () => {
                gsap.to(thisFrame, {
                    display: "none"
                })
                const frameSrc = thisFrame.src.replace('&autoplay=1', '')
                thisFrame.src = frameSrc
            }
        },"-=.4")
        vidModal.to(".video-bg", {
          scale: .8,
          y: "-110%",
          rotate: -15,
          duration: 1,
          ease: "expo",
          onStart: ()=> {
               gsap.to("#video-wrap", {
                    pointerEvents: "none",
                })
                if(!isMobile()) {
                    smoother.paused(false)
                }
                delete  closeVid.dataset.open
            },
            onComplete: ()=> {
                gsap.set(thisVideo, {zIndex: "auto"})
            },
        })
        vidModal.to("#menu", {
            opacity: 1,
            duration: .5,
            ease: "power4",
            pointerEvents: "auto",
        }, "<")
    })


}




